import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://portal-test.goya.com/oms2/#/login');
  await page.getByPlaceholder('Username').click();
  await page.getByPlaceholder('Username').fill('013506');
  await page.getByPlaceholder('Username').press('Tab');
  await page.getByPlaceholder('Password').fill('Pwd@013506');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Order', exact: true }).click();
  await page.getByRole('searchbox', { name: 'Customer' }).click();
  await page.getByRole('option', { name: '713742-ACME 1893' }).locator('div').filter({ hasText: '713742-ACME 1893' }).click();
  await page.getByRole('textbox', { name: 'Item / UPC#' }).click();
  await page.getByRole('textbox', { name: 'Item / UPC#' }).fill('2365');
  await page.getByPlaceholder('Cases').fill('11');
  await page.getByPlaceholder('Cases').press('Tab');
  await page.getByRole('textbox', { name: 'Item / UPC#' }).fill('1107');
  await page.getByPlaceholder('Cases').press('Tab');
  await page.getByRole('textbox', { name: 'Item / UPC#' }).click();
  await page.getByRole('textbox', { name: 'Item / UPC#' }).fill('2465');
  await page.getByPlaceholder('Cases').press('Tab');
  await page.getByRole('textbox', { name: 'Item / UPC#' }).fill('2479');
  await page.getByPlaceholder('Cases').press('Tab');
  await page.getByRole('textbox', { name: 'Item / UPC#' }).fill('2491');
  await page.getByPlaceholder('Cases').fill('2');
  await page.getByPlaceholder('Cases').press('Tab');
  await page.getByRole('textbox', { name: 'Item / UPC#' }).click();
  await page.getByRole('textbox', { name: 'Item / UPC#' }).fill('2630');
  await page.getByPlaceholder('Cases').press('Tab');
  await page.getByRole('textbox', { name: 'Item / UPC#' }).fill('2345');
  await page.getByPlaceholder('Cases').fill('3');
  await page.getByPlaceholder('Cases').press('Tab');
  await page.getByRole('textbox', { name: 'Item / UPC#' }).fill('1195');
  await page.getByPlaceholder('Cases').fill('4');
  await page.getByPlaceholder('Cases').press('Tab');
  await page.getByRole('textbox', { name: 'Item / UPC#' }).click();
  await page.getByRole('textbox', { name: 'Item / UPC#' }).fill('1222');
  await page.getByPlaceholder('Cases').press('Tab');
  await page.getByRole('textbox', { name: 'Item / UPC#' }).fill('2490');
  await page.getByPlaceholder('Cases').fill('4');
  await page.getByPlaceholder('Cases').press('Tab');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Continue Without Merge' }).click();
  await page.locator('#duplicateOrderModalPopup').getByRole('checkbox').check();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.locator('#duplicateOrderModalPopup').getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: '013506-CARLOS MORATO' }).click();
  await page.getByRole('link', { name: 'Logout' }).click();
});